# Generated by Django 5.0.6 on 2024-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_rentalpost_is_vacant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3000000, max_digits=10),
        ),
    ]
