# Generated by Django 5.0.6 on 2024-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('requested', 'Refund Requested'), ('processed', 'Refund Processed')], default='none', max_length=10),
        ),
    ]
